FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
RUN apt-get update && apt-get install -y nodejs npm
COPY ["devpodcasts.ui.csproj", "."]
RUN dotnet restore
COPY . .
RUN dotnet publish "devpodcasts.ui.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:5000
EXPOSE 5000
ENTRYPOINT ["dotnet", "devpodcasts.ui.dll"]
